version: '3.6'
services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: ab_mosquitto
    restart: always
    volumes:
      - ./mqtt/mosquitto.conf:/mqtt/mosquitto.conf
    networks:
     as_blinds_se4as: {}
    ports:
      - "1883:1883"
      - "9001:9001"
    
      
  main-app:
    build:
     dockerfile: dockerfile
    depends_on:
      - influxdb
      - mqtt
    networks:
     as_blinds_se4as: {}

  influxdb:
    image: influxdb:latest
    container_name: influxdb_se4as
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=se4as_token
      - DOCKER_INFLUXDB_INIT_ORG=se4as
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
    networks:
     as_blinds_se4as: {}
    
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mqtt
    links:
      - influxdb
    ports:
      - '8125:8125'    
    networks:
      as_blinds_se4as: {}


volumes:
  influxdb_data: {}

networks:
  as_blinds_se4as:
   driver: bridge
   ipam: 
    config:
     - subnet: 172.20.0.0/16
